"""empty message

Revision ID: 10244f156150
Revises: 8a6d9f949bc0
Create Date: 2022-10-05 19:00:11.986080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10244f156150'
down_revision = '8a6d9f949bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'location',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('profile', 'biography',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('profile', 'image_url',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('profile', 'cloudinary_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'cloudinary_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('profile', 'image_url',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('profile', 'biography',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('profile', 'location',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
