"""empty message

Revision ID: aefadbb496f5
Revises: 4fe3230fac6d
Create Date: 2022-09-22 13:00:50.826308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefadbb496f5'
down_revision = '4fe3230fac6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_caption_key', 'post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_caption_key', 'post', ['caption'])
    # ### end Alembic commands ###
