"""empty message

Revision ID: b6d810667988
Revises: bd79bbccdfb0
Create Date: 2022-10-07 14:27:06.032952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d810667988'
down_revision = 'bd79bbccdfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'caption',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=800),
               existing_nullable=False)
    op.alter_column('post', 'ingredients',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=800),
               existing_nullable=False)
    op.alter_column('post', 'preparation',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=800),
               existing_nullable=False)
    op.alter_column('profile', 'location',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('profile', 'biography',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('profile', 'cloudinary_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=220),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'cloudinary_id',
               existing_type=sa.String(length=220),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('profile', 'biography',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('profile', 'location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('post', 'preparation',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('post', 'ingredients',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('post', 'caption',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###
